
test:2.7:
  image: python:2.7
  
  before_script:
    - python -V
    - pip install -r requirements.txt
  
  script:
    - pytest -v

test:3.6:
  image: python:3.6
  
  before_script:
    - python -V
    - pip install -r requirements.txt
  
  script:
    - pytest -v

test:3.7:
  image: python:3.7
  
  before_script:
    - python -V
    - pip install -r requirements.txt
  
  script:
    - pytest -v

